### ISSUE TITLE
the arm can  not move 

### ISSUE THREAD

**Issue by weakenleg** [ashishagg70/ur5_ROS-Gazebo_melodic#1]
the terminal print warn when the red box cross the camera
[ WARN] [1595472688.063235819, 117.205000000]: The complete state of the robot is not yet known. Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8
[ WARN] [1595472695.682415864, 118.245000000]: The complete state of the robot is not yet known. Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8
[ WARN] [1595472703.519119242, 119.245000000]: The complete state of the robot is not yet known. Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8
also, some error
[ERROR] [1595471981.780210349, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/shoulder_pan_joint
[ERROR] [1595471981.784470315, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/shoulder_lift_joint
[ERROR] [1595471981.788446378, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/elbow_joint
[ERROR] [1595471981.794961431, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/wrist_1_joint
[ERROR] [1625905950.989653, 67.831000]: bad callback: <bound method ur5_vision.image_callback of <__main__.ur5_vision instance at 0x7f2ed0eeba50>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/zg/ur_ws/src/ur5_ROS-Gazebo_melodic/ur5_ROS-Gazebo/ur5_vision.py", line 63, in image_callback
    (_, cnts, _) = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack
I can't solve the problem,please help me,thanks.

**Comment by hxn8439** [comment]
I have the same problem too. The robot arm suppose to move after executing 
roslaunch ur5_notebook initialize.launch

So, I also execute python testvisionplanner.py and testmove2.py but endup with this error return. 

[ERROR] [1630771695.765029]: Unable to immediately register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.

so the error is happening at the master node communication.

**Comment by slamlixiaodong** [comment]
when  I  add gazebo_ros_vacuum_gripper plugin  in melodic version, I meet the same error "The complete state of the robot is not yet known. Missing". Did you have solved this problem?

**Comment by ashishagg70** [comment]
@weakenleg  No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/elbow_joint can be ignored.
This value error is happening because (, cnts, _) should be (_, cnts, _).

**Comment by ashishagg70** [comment]
@weakenleg ERROR : "No p gain specified for pid. Namespace ..." can be ignored. Value error is happeing because (, cnts, _) should be ( _, cnts, _). openCV version used for the project  is 3.2.0

> the terminal print warn when the red box cross the camera [ WARN] [1595472688.063235819, 117.205000000]: The complete state of the robot is not yet known. Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8 [ WARN] [1595472695.682415864, 118.245000000]: The complete state of the robot is not yet known. Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8 [ WARN] [1595472703.519119242, 119.245000000]: The complete state of the robot is not yet known. Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8 also, some error [ERROR] [1595471981.780210349, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/shoulder_pan_joint [ERROR] [1595471981.784470315, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/shoulder_lift_joint [ERROR] [1595471981.788446378, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/elbow_joint [ERROR] [1595471981.794961431, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/wrist_1_joint [ERROR] [1625905950.989653, 67.831000]: bad callback: <bound method ur5_vision.image_callback of <**main**.ur5_vision instance at 0x7f2ed0eeba50>> Traceback (most recent call last): File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback cb(msg) File "/home/zg/ur_ws/src/ur5_ROS-Gazebo_melodic/ur5_ROS-Gazebo/ur5_vision.py", line 63, in image_callback (_, cnts, _) = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) ValueError: need more than 2 values to unpack I can't solve the problem,please help me,thanks.
